SET DEFINE OFF

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (8.0, 'The Social Network', 'Drama', to_date('10/01/2010', 'MM/DD/YYYY'), 'Columbia Pictures', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (8.0, 'The Social Network', 'Drama', to_date('10/01/2010', 'MM/DD/YYYY'), 'Columbia Pictures', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (8.0, 'The Social Network', 'Drama', to_date('10/01/2010', 'MM/DD/YYYY'), 'Columbia Pictures', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (6.0, 'Moonrise Kingdom', 'Drama Comedy', to_date('05/25/2012', 'MM/DD/YYYY'), 'Focus Features', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (5.0, 'La La Land', 'Musical', to_date('12/09/2016', 'MM/DD/YYYY'), 'Summit Entertainment', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (5.0, 'La La Land', 'Musical', to_date('12/09/2016', 'MM/DD/YYYY'), 'Summit Entertainment', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (5.0, 'La La Land', 'Musical', to_date('12/09/2016', 'MM/DD/YYYY'), 'Summit Entertainment', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (5.0, 'La La Land', 'Musical', to_date('12/09/2016', 'MM/DD/YYYY'), 'Summit Entertainment', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (8.0, 'The Social Network', 'Drama', to_date('10/01/2010', 'MM/DD/YYYY'), 'Columbia Pictures', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (1.0, 'Way of Kings', 'Fantasy', to_date('08/31/2010', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (2.0, 'Words of Radiance', 'Fantasy', to_date('03/04/2014', 'MM/DD/YYYY'), 'Tor Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (3.0, 'Inception', 'Science Fiction/Thriller', to_date('07/08/2010', 'MM/DD/YYYY'), 'Warner Bros', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (4.0, 'Infinite Jest', 'Tragicomedy', to_date('02/01/1996', 'MM/DD/YYYY'), 'Brown, Little, and Co.', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (5.0, 'La La Land', 'Musical', to_date('12/09/2016', 'MM/DD/YYYY'), 'Summit Entertainment', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (5.0, 'La La Land', 'Musical', to_date('12/09/2016', 'MM/DD/YYYY'), 'Summit Entertainment', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (6.0, 'Moonrise Kingdom', 'Drama Comedy', to_date('05/25/2012', 'MM/DD/YYYY'), 'Focus Features', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (6.0, 'Moonrise Kingdom', 'Drama Comedy', to_date('05/25/2012', 'MM/DD/YYYY'), 'Focus Features', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (6.0, 'Moonrise Kingdom', 'Drama Comedy', to_date('05/25/2012', 'MM/DD/YYYY'), 'Focus Features', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (7.0, 'The Name of the Wind', 'Fantasy', to_date('03/27/2007', 'MM/DD/YYYY'), 'DAW Books', 'BOOK');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (8.0, 'The Social Network', 'Drama', to_date('10/01/2010', 'MM/DD/YYYY'), 'Columbia Pictures', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (8.0, 'The Social Network', 'Drama', to_date('10/01/2010', 'MM/DD/YYYY'), 'Columbia Pictures', 'DVD');

INSERT INTO CATALOG_ITEM (CATALOG_ITEM_ID, TITLE, DESCRIPTION, RELEASE_DATE, PUBLISHER, TYPE) 
VALUES (8.0, 'The Social Network', 'Drama', to_date('10/01/2010', 'MM/DD/YYYY'), 'Columbia Pictures', 'DVD');

-- Import Data into table CATALOG_ITEM from file C:\Users\tpenn1\AppData\Roaming\SQL Developer\mywork\DBST651\Case_Study_Library_Data.xlsx . Task successful and sent to worksheet.

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (1.0, 1280.0, '9780765365279');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (2.0, 1328.0, '9780765365286');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (4.0, 1079.0, '9780316066525');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

INSERT INTO BOOK (CATALOG_ITEM_ID, PAGE_LENGTH, ISBN) 
VALUES (7.0, 722.0, '9780756404079');

-- Import Data into table BOOK from file C:\Users\tpenn1\AppData\Roaming\SQL Developer\mywork\DBST651\Case_Study_Library_Data.xlsx . Task successful and sent to worksheet.

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (8.0, '2:01');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (8.0, '2:01');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (8.0, '2:01');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (6.0, '1:34');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (5.0, '2:08');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (5.0, '2:08');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (5.0, '2:08');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (5.0, '2:08');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (8.0, '2:01');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (3.0, '2:28');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (5.0, '2:08');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (5.0, '2:08');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (6.0, '1:34');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (6.0, '1:34');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (6.0, '1:34');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (8.0, '2:01');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (8.0, '2:01');

INSERT INTO DVD (CATALOG_ITEM_ID, DVD_LENGTH) 
VALUES (8.0, '2:01');

-- Import Data into table DVD from file C:\Users\tpenn1\AppData\Roaming\SQL Developer\mywork\DBST651\Case_Study_Library_Data.xlsx . Task successful and sent to worksheet.

